##端口号
server:
  port: 8004
## mybatis配置
mybatis:
  mapper-locations: classpath*:com/phy/vwechat/dao/mapping/*.xml
  typeAliasesPackage: com.phy.vwechat.model
##日志等级
logging:
  level:
    com.phy.vwechat.dao : debug
##数据源
spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/vwechat?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://123.57.22.91:3306/vwechat?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    db-name: vwechat
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver